name: Test

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.14.0
          target-platform: x86_64-linux
      - run: zig build test
